version: "3.9"

services:
  whisper-api:
    image: morioka/tiny-openai-embeddings-api
    build: .
    container_name: embeddings-api
    restart: unless-stopped
    init: true
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: "./model"
        target: "/app/model"